#include "parameter.h"
int parse(NetParameter * netParameter)
{
	CHECK_EXPR_RET(strlen("LeNet") > PARSE_STR_NAME_SIZE - 1,-1);
	strcpy(netParameter->name,"LeNet");
	netParameter->layer = (LayerParameter *)malloc(sizeof(LayerParameter)*11);
	netParameter->layer_size = 11;
	CHECK_EXPR_RET(strlen("mnist") > PARSE_STR_NAME_SIZE - 1,-1);
	strcpy(netParameter->layer[0].name,"mnist");
	CHECK_EXPR_RET(strlen("Data") > PARSE_STR_NAME_SIZE - 1,-1);
	strcpy(netParameter->layer[0].type,"Data");
	netParameter->layer[0].top = (char (*)[PARSE_STR_NAME_SIZE])malloc(PARSE_STR_NAME_SIZE*2);
	netParameter->layer[0].top_size = 2;
	CHECK_EXPR_RET(strlen("data") > PARSE_STR_NAME_SIZE - 1,-1);
	strcpy(netParameter->layer[0].top[0],"data");
	CHECK_EXPR_RET(strlen("label") > PARSE_STR_NAME_SIZE - 1,-1);
	strcpy(netParameter->layer[0].top[1],"label");
	netParameter->layer[0].include = (NetStateRule *)malloc(sizeof(NetStateRule)*1);
	netParameter->layer[0].include_size = 1;
	netParameter->layer[0].include[0].phase = TRAIN;
	netParameter->layer[0].transform_param.scale = 0.00390625;
	CHECK_EXPR_RET(strlen("examples/my_mnist/mean.binaryproto") > PARSE_STR_NAME_SIZE - 1,-1);
	strcpy(netParameter->layer[0].transform_param.mean_file,"examples/my_mnist/mean.binaryproto");
	CHECK_EXPR_RET(strlen("examples/my_mnist/mnist_train_lmdb") > PARSE_STR_NAME_SIZE - 1,-1);
	strcpy(netParameter->layer[0].data_param.source,"examples/my_mnist/mnist_train_lmdb");
	netParameter->layer[0].data_param.batch_size = 64;
	netParameter->layer[0].data_param.backend = DataParameter_DB_LMDB;
	CHECK_EXPR_RET(strlen("mnist") > PARSE_STR_NAME_SIZE - 1,-1);
	strcpy(netParameter->layer[1].name,"mnist");
	CHECK_EXPR_RET(strlen("Data") > PARSE_STR_NAME_SIZE - 1,-1);
	strcpy(netParameter->layer[1].type,"Data");
	netParameter->layer[1].top = (char (*)[PARSE_STR_NAME_SIZE])malloc(PARSE_STR_NAME_SIZE*2);
	netParameter->layer[1].top_size = 2;
	CHECK_EXPR_RET(strlen("data") > PARSE_STR_NAME_SIZE - 1,-1);
	strcpy(netParameter->layer[1].top[0],"data");
	CHECK_EXPR_RET(strlen("label") > PARSE_STR_NAME_SIZE - 1,-1);
	strcpy(netParameter->layer[1].top[1],"label");
	netParameter->layer[1].include = (NetStateRule *)malloc(sizeof(NetStateRule)*1);
	netParameter->layer[1].include_size = 1;
	netParameter->layer[1].include[0].phase = TEST;
	netParameter->layer[1].transform_param.scale = 0.00390625;
	CHECK_EXPR_RET(strlen("examples/my_mnist/mean.binaryproto") > PARSE_STR_NAME_SIZE - 1,-1);
	strcpy(netParameter->layer[1].transform_param.mean_file,"examples/my_mnist/mean.binaryproto");
	CHECK_EXPR_RET(strlen("examples/my_mnist/mnist_test_lmdb") > PARSE_STR_NAME_SIZE - 1,-1);
	strcpy(netParameter->layer[1].data_param.source,"examples/my_mnist/mnist_test_lmdb");
	netParameter->layer[1].data_param.batch_size = 100;
	netParameter->layer[1].data_param.backend = DataParameter_DB_LMDB;
	CHECK_EXPR_RET(strlen("conv1") > PARSE_STR_NAME_SIZE - 1,-1);
	strcpy(netParameter->layer[2].name,"conv1");
	CHECK_EXPR_RET(strlen("Convolution") > PARSE_STR_NAME_SIZE - 1,-1);
	strcpy(netParameter->layer[2].type,"Convolution");
	netParameter->layer[2].bottom = (char (*)[PARSE_STR_NAME_SIZE])malloc(PARSE_STR_NAME_SIZE*1);
	netParameter->layer[2].bottom_size = 1;
	CHECK_EXPR_RET(strlen("data") > PARSE_STR_NAME_SIZE - 1,-1);
	strcpy(netParameter->layer[2].bottom[0],"data");
	netParameter->layer[2].top = (char (*)[PARSE_STR_NAME_SIZE])malloc(PARSE_STR_NAME_SIZE*1);
	netParameter->layer[2].top_size = 1;
	CHECK_EXPR_RET(strlen("conv1") > PARSE_STR_NAME_SIZE - 1,-1);
	strcpy(netParameter->layer[2].top[0],"conv1");
	netParameter->layer[2].param = (ParamSpec *)malloc(sizeof(ParamSpec)*2);
	netParameter->layer[2].param_size = 2;
	netParameter->layer[2].param[0].lr_mult = 1;
	netParameter->layer[2].param[1].lr_mult = 2;
	netParameter->layer[2].convolution_param.num_output = 20;
	netParameter->layer[2].convolution_param.kernel_w = 5;
	netParameter->layer[2].convolution_param.kernel_h = 5;
	netParameter->layer[2].convolution_param.stride = (UINT32 *)malloc(sizeof(UINT32)*1);
	netParameter->layer[2].convolution_param.stride_size = 1;
	netParameter->layer[2].convolution_param.stride[0] = 1;
	CHECK_EXPR_RET(strlen("xavier") > PARSE_STR_NAME_SIZE - 1,-1);
	strcpy(netParameter->layer[2].convolution_param.weight_filler.type,"xavier");
	CHECK_EXPR_RET(strlen("constant") > PARSE_STR_NAME_SIZE - 1,-1);
	strcpy(netParameter->layer[2].convolution_param.bias_filler.type,"constant");
	CHECK_EXPR_RET(strlen("pool1") > PARSE_STR_NAME_SIZE - 1,-1);
	strcpy(netParameter->layer[3].name,"pool1");
	CHECK_EXPR_RET(strlen("Pooling") > PARSE_STR_NAME_SIZE - 1,-1);
	strcpy(netParameter->layer[3].type,"Pooling");
	netParameter->layer[3].bottom = (char (*)[PARSE_STR_NAME_SIZE])malloc(PARSE_STR_NAME_SIZE*1);
	netParameter->layer[3].bottom_size = 1;
	CHECK_EXPR_RET(strlen("conv1") > PARSE_STR_NAME_SIZE - 1,-1);
	strcpy(netParameter->layer[3].bottom[0],"conv1");
	netParameter->layer[3].top = (char (*)[PARSE_STR_NAME_SIZE])malloc(PARSE_STR_NAME_SIZE*1);
	netParameter->layer[3].top_size = 1;
	CHECK_EXPR_RET(strlen("pool1") > PARSE_STR_NAME_SIZE - 1,-1);
	strcpy(netParameter->layer[3].top[0],"pool1");
	netParameter->layer[3].pooling_param.pool = PoolingParameter_PoolMethod_MAX;
	netParameter->layer[3].pooling_param.kernel_size = 2;
	netParameter->layer[3].pooling_param.stride = 2;
	CHECK_EXPR_RET(strlen("conv2") > PARSE_STR_NAME_SIZE - 1,-1);
	strcpy(netParameter->layer[4].name,"conv2");
	CHECK_EXPR_RET(strlen("Convolution") > PARSE_STR_NAME_SIZE - 1,-1);
	strcpy(netParameter->layer[4].type,"Convolution");
	netParameter->layer[4].bottom = (char (*)[PARSE_STR_NAME_SIZE])malloc(PARSE_STR_NAME_SIZE*1);
	netParameter->layer[4].bottom_size = 1;
	CHECK_EXPR_RET(strlen("pool1") > PARSE_STR_NAME_SIZE - 1,-1);
	strcpy(netParameter->layer[4].bottom[0],"pool1");
	netParameter->layer[4].top = (char (*)[PARSE_STR_NAME_SIZE])malloc(PARSE_STR_NAME_SIZE*1);
	netParameter->layer[4].top_size = 1;
	CHECK_EXPR_RET(strlen("conv2") > PARSE_STR_NAME_SIZE - 1,-1);
	strcpy(netParameter->layer[4].top[0],"conv2");
	netParameter->layer[4].param = (ParamSpec *)malloc(sizeof(ParamSpec)*2);
	netParameter->layer[4].param_size = 2;
	netParameter->layer[4].param[0].lr_mult = 1;
	netParameter->layer[4].param[1].lr_mult = 2;
	netParameter->layer[4].convolution_param.num_output = 50;
	netParameter->layer[4].convolution_param.kernel_w = 5;
	netParameter->layer[4].convolution_param.kernel_h = 5;
	netParameter->layer[4].convolution_param.stride = (UINT32 *)malloc(sizeof(UINT32)*1);
	netParameter->layer[4].convolution_param.stride_size = 1;
	netParameter->layer[4].convolution_param.stride[0] = 1;
	CHECK_EXPR_RET(strlen("xavier") > PARSE_STR_NAME_SIZE - 1,-1);
	strcpy(netParameter->layer[4].convolution_param.weight_filler.type,"xavier");
	CHECK_EXPR_RET(strlen("constant") > PARSE_STR_NAME_SIZE - 1,-1);
	strcpy(netParameter->layer[4].convolution_param.bias_filler.type,"constant");
	CHECK_EXPR_RET(strlen("pool2") > PARSE_STR_NAME_SIZE - 1,-1);
	strcpy(netParameter->layer[5].name,"pool2");
	CHECK_EXPR_RET(strlen("Pooling") > PARSE_STR_NAME_SIZE - 1,-1);
	strcpy(netParameter->layer[5].type,"Pooling");
	netParameter->layer[5].bottom = (char (*)[PARSE_STR_NAME_SIZE])malloc(PARSE_STR_NAME_SIZE*1);
	netParameter->layer[5].bottom_size = 1;
	CHECK_EXPR_RET(strlen("conv2") > PARSE_STR_NAME_SIZE - 1,-1);
	strcpy(netParameter->layer[5].bottom[0],"conv2");
	netParameter->layer[5].top = (char (*)[PARSE_STR_NAME_SIZE])malloc(PARSE_STR_NAME_SIZE*1);
	netParameter->layer[5].top_size = 1;
	CHECK_EXPR_RET(strlen("pool2") > PARSE_STR_NAME_SIZE - 1,-1);
	strcpy(netParameter->layer[5].top[0],"pool2");
	netParameter->layer[5].pooling_param.pool = PoolingParameter_PoolMethod_MAX;
	netParameter->layer[5].pooling_param.kernel_size = 2;
	netParameter->layer[5].pooling_param.stride = 2;
	CHECK_EXPR_RET(strlen("ip1") > PARSE_STR_NAME_SIZE - 1,-1);
	strcpy(netParameter->layer[6].name,"ip1");
	CHECK_EXPR_RET(strlen("InnerProduct") > PARSE_STR_NAME_SIZE - 1,-1);
	strcpy(netParameter->layer[6].type,"InnerProduct");
	netParameter->layer[6].bottom = (char (*)[PARSE_STR_NAME_SIZE])malloc(PARSE_STR_NAME_SIZE*1);
	netParameter->layer[6].bottom_size = 1;
	CHECK_EXPR_RET(strlen("pool2") > PARSE_STR_NAME_SIZE - 1,-1);
	strcpy(netParameter->layer[6].bottom[0],"pool2");
	netParameter->layer[6].top = (char (*)[PARSE_STR_NAME_SIZE])malloc(PARSE_STR_NAME_SIZE*1);
	netParameter->layer[6].top_size = 1;
	CHECK_EXPR_RET(strlen("ip1") > PARSE_STR_NAME_SIZE - 1,-1);
	strcpy(netParameter->layer[6].top[0],"ip1");
	netParameter->layer[6].param = (ParamSpec *)malloc(sizeof(ParamSpec)*2);
	netParameter->layer[6].param_size = 2;
	netParameter->layer[6].param[0].lr_mult = 1;
	netParameter->layer[6].param[1].lr_mult = 2;
	netParameter->layer[6].inner_product_param.num_output = 500;
	CHECK_EXPR_RET(strlen("xavier") > PARSE_STR_NAME_SIZE - 1,-1);
	strcpy(netParameter->layer[6].inner_product_param.weight_filler.type,"xavier");
	CHECK_EXPR_RET(strlen("constant") > PARSE_STR_NAME_SIZE - 1,-1);
	strcpy(netParameter->layer[6].inner_product_param.bias_filler.type,"constant");
	CHECK_EXPR_RET(strlen("relu1") > PARSE_STR_NAME_SIZE - 1,-1);
	strcpy(netParameter->layer[7].name,"relu1");
	CHECK_EXPR_RET(strlen("ReLU") > PARSE_STR_NAME_SIZE - 1,-1);
	strcpy(netParameter->layer[7].type,"ReLU");
	netParameter->layer[7].bottom = (char (*)[PARSE_STR_NAME_SIZE])malloc(PARSE_STR_NAME_SIZE*1);
	netParameter->layer[7].bottom_size = 1;
	CHECK_EXPR_RET(strlen("ip1") > PARSE_STR_NAME_SIZE - 1,-1);
	strcpy(netParameter->layer[7].bottom[0],"ip1");
	netParameter->layer[7].top = (char (*)[PARSE_STR_NAME_SIZE])malloc(PARSE_STR_NAME_SIZE*1);
	netParameter->layer[7].top_size = 1;
	CHECK_EXPR_RET(strlen("ip1") > PARSE_STR_NAME_SIZE - 1,-1);
	strcpy(netParameter->layer[7].top[0],"ip1");
	CHECK_EXPR_RET(strlen("ip2") > PARSE_STR_NAME_SIZE - 1,-1);
	strcpy(netParameter->layer[8].name,"ip2");
	CHECK_EXPR_RET(strlen("InnerProduct") > PARSE_STR_NAME_SIZE - 1,-1);
	strcpy(netParameter->layer[8].type,"InnerProduct");
	netParameter->layer[8].bottom = (char (*)[PARSE_STR_NAME_SIZE])malloc(PARSE_STR_NAME_SIZE*1);
	netParameter->layer[8].bottom_size = 1;
	CHECK_EXPR_RET(strlen("ip1") > PARSE_STR_NAME_SIZE - 1,-1);
	strcpy(netParameter->layer[8].bottom[0],"ip1");
	netParameter->layer[8].top = (char (*)[PARSE_STR_NAME_SIZE])malloc(PARSE_STR_NAME_SIZE*1);
	netParameter->layer[8].top_size = 1;
	CHECK_EXPR_RET(strlen("ip2") > PARSE_STR_NAME_SIZE - 1,-1);
	strcpy(netParameter->layer[8].top[0],"ip2");
	netParameter->layer[8].param = (ParamSpec *)malloc(sizeof(ParamSpec)*2);
	netParameter->layer[8].param_size = 2;
	netParameter->layer[8].param[0].lr_mult = 1;
	netParameter->layer[8].param[1].lr_mult = 2;
	netParameter->layer[8].inner_product_param.num_output = 2;
	CHECK_EXPR_RET(strlen("xavier") > PARSE_STR_NAME_SIZE - 1,-1);
	strcpy(netParameter->layer[8].inner_product_param.weight_filler.type,"xavier");
	CHECK_EXPR_RET(strlen("constant") > PARSE_STR_NAME_SIZE - 1,-1);
	strcpy(netParameter->layer[8].inner_product_param.bias_filler.type,"constant");
	CHECK_EXPR_RET(strlen("accuracy") > PARSE_STR_NAME_SIZE - 1,-1);
	strcpy(netParameter->layer[9].name,"accuracy");
	CHECK_EXPR_RET(strlen("Accuracy") > PARSE_STR_NAME_SIZE - 1,-1);
	strcpy(netParameter->layer[9].type,"Accuracy");
	netParameter->layer[9].bottom = (char (*)[PARSE_STR_NAME_SIZE])malloc(PARSE_STR_NAME_SIZE*2);
	netParameter->layer[9].bottom_size = 2;
	CHECK_EXPR_RET(strlen("ip2") > PARSE_STR_NAME_SIZE - 1,-1);
	strcpy(netParameter->layer[9].bottom[0],"ip2");
	CHECK_EXPR_RET(strlen("label") > PARSE_STR_NAME_SIZE - 1,-1);
	strcpy(netParameter->layer[9].bottom[1],"label");
	netParameter->layer[9].top = (char (*)[PARSE_STR_NAME_SIZE])malloc(PARSE_STR_NAME_SIZE*1);
	netParameter->layer[9].top_size = 1;
	CHECK_EXPR_RET(strlen("accuracy") > PARSE_STR_NAME_SIZE - 1,-1);
	strcpy(netParameter->layer[9].top[0],"accuracy");
	netParameter->layer[9].include = (NetStateRule *)malloc(sizeof(NetStateRule)*1);
	netParameter->layer[9].include_size = 1;
	netParameter->layer[9].include[0].phase = TEST;
	CHECK_EXPR_RET(strlen("loss") > PARSE_STR_NAME_SIZE - 1,-1);
	strcpy(netParameter->layer[10].name,"loss");
	CHECK_EXPR_RET(strlen("SoftmaxWithLoss") > PARSE_STR_NAME_SIZE - 1,-1);
	strcpy(netParameter->layer[10].type,"SoftmaxWithLoss");
	netParameter->layer[10].bottom = (char (*)[PARSE_STR_NAME_SIZE])malloc(PARSE_STR_NAME_SIZE*2);
	netParameter->layer[10].bottom_size = 2;
	CHECK_EXPR_RET(strlen("ip2") > PARSE_STR_NAME_SIZE - 1,-1);
	strcpy(netParameter->layer[10].bottom[0],"ip2");
	CHECK_EXPR_RET(strlen("label") > PARSE_STR_NAME_SIZE - 1,-1);
	strcpy(netParameter->layer[10].bottom[1],"label");
	netParameter->layer[10].top = (char (*)[PARSE_STR_NAME_SIZE])malloc(PARSE_STR_NAME_SIZE*1);
	netParameter->layer[10].top_size = 1;
	CHECK_EXPR_RET(strlen("loss") > PARSE_STR_NAME_SIZE - 1,-1);
	strcpy(netParameter->layer[10].top[0],"loss");
	netParameter->force_backward = false;
	netParameter->debug_info = false;
	netParameter->layer[10].blobs = (BlobProto *)malloc(sizeof(BlobProto)*1);
	netParameter->layer[10].blobs_size = 1;
	netParameter->layer[10].blobs[0].width = 0;
	netParameter->layer[10].blobs[0].height = 0;
	netParameter->layer[10].blobs[0].channels = 0;
	netParameter->layer[10].blobs[0].num = 0;
	netParameter->layer[10].param = (ParamSpec *)malloc(sizeof(ParamSpec)*1);
	netParameter->layer[10].param_size = 1;
	netParameter->layer[10].param[0].decay_mult = 1.0;
	netParameter->layer[10].param[0].lr_mult = 1.0;
	netParameter->layer[9].accuracy_param.axis = 1;
	netParameter->layer[9].accuracy_param.top_k = 1;
	netParameter->layer[9].blobs = (BlobProto *)malloc(sizeof(BlobProto)*1);
	netParameter->layer[9].blobs_size = 1;
	netParameter->layer[9].blobs[0].width = 0;
	netParameter->layer[9].blobs[0].height = 0;
	netParameter->layer[9].blobs[0].channels = 0;
	netParameter->layer[9].blobs[0].num = 0;
	netParameter->layer[9].param = (ParamSpec *)malloc(sizeof(ParamSpec)*1);
	netParameter->layer[9].param_size = 1;
	netParameter->layer[9].param[0].decay_mult = 1.0;
	netParameter->layer[9].param[0].lr_mult = 1.0;
	netParameter->layer[8].inner_product_param.bias_term = true;
	netParameter->layer[8].inner_product_param.axis = 1;
	netParameter->layer[8].inner_product_param.transpose = false;
	netParameter->layer[8].inner_product_param.bias_filler.value = 0;
	netParameter->layer[8].inner_product_param.bias_filler.min = 0;
	netParameter->layer[8].inner_product_param.bias_filler.max = 1;
	netParameter->layer[8].inner_product_param.bias_filler.mean = 0;
	netParameter->layer[8].inner_product_param.bias_filler.std = 1;
	netParameter->layer[8].inner_product_param.bias_filler.sparse = -1;
	netParameter->layer[8].inner_product_param.bias_filler.variance_norm = FillerParameter_VarianceNorm_FAN_IN;
	netParameter->layer[8].inner_product_param.weight_filler.value = 0;
	netParameter->layer[8].inner_product_param.weight_filler.min = 0;
	netParameter->layer[8].inner_product_param.weight_filler.max = 1;
	netParameter->layer[8].inner_product_param.weight_filler.mean = 0;
	netParameter->layer[8].inner_product_param.weight_filler.std = 1;
	netParameter->layer[8].inner_product_param.weight_filler.sparse = -1;
	netParameter->layer[8].inner_product_param.weight_filler.variance_norm = FillerParameter_VarianceNorm_FAN_IN;
	netParameter->layer[8].param[1].decay_mult = 1.0;
	netParameter->layer[8].param[0].decay_mult = 1.0;
	netParameter->layer[8].blobs = (BlobProto *)malloc(sizeof(BlobProto)*1);
	netParameter->layer[8].blobs_size = 1;
	netParameter->layer[8].blobs[0].width = 0;
	netParameter->layer[8].blobs[0].height = 0;
	netParameter->layer[8].blobs[0].channels = 0;
	netParameter->layer[8].blobs[0].num = 0;
	netParameter->layer[7].relu_param.engine = ReLUParameter_Engine_DEFAULT;
	netParameter->layer[7].relu_param.negative_slope = 0;
	netParameter->layer[7].blobs = (BlobProto *)malloc(sizeof(BlobProto)*1);
	netParameter->layer[7].blobs_size = 1;
	netParameter->layer[7].blobs[0].width = 0;
	netParameter->layer[7].blobs[0].height = 0;
	netParameter->layer[7].blobs[0].channels = 0;
	netParameter->layer[7].blobs[0].num = 0;
	netParameter->layer[7].param = (ParamSpec *)malloc(sizeof(ParamSpec)*1);
	netParameter->layer[7].param_size = 1;
	netParameter->layer[7].param[0].decay_mult = 1.0;
	netParameter->layer[7].param[0].lr_mult = 1.0;
	netParameter->layer[6].inner_product_param.bias_term = true;
	netParameter->layer[6].inner_product_param.axis = 1;
	netParameter->layer[6].inner_product_param.transpose = false;
	netParameter->layer[6].inner_product_param.bias_filler.value = 0;
	netParameter->layer[6].inner_product_param.bias_filler.min = 0;
	netParameter->layer[6].inner_product_param.bias_filler.max = 1;
	netParameter->layer[6].inner_product_param.bias_filler.mean = 0;
	netParameter->layer[6].inner_product_param.bias_filler.std = 1;
	netParameter->layer[6].inner_product_param.bias_filler.sparse = -1;
	netParameter->layer[6].inner_product_param.bias_filler.variance_norm = FillerParameter_VarianceNorm_FAN_IN;
	netParameter->layer[6].inner_product_param.weight_filler.value = 0;
	netParameter->layer[6].inner_product_param.weight_filler.min = 0;
	netParameter->layer[6].inner_product_param.weight_filler.max = 1;
	netParameter->layer[6].inner_product_param.weight_filler.mean = 0;
	netParameter->layer[6].inner_product_param.weight_filler.std = 1;
	netParameter->layer[6].inner_product_param.weight_filler.sparse = -1;
	netParameter->layer[6].inner_product_param.weight_filler.variance_norm = FillerParameter_VarianceNorm_FAN_IN;
	netParameter->layer[6].param[1].decay_mult = 1.0;
	netParameter->layer[6].param[0].decay_mult = 1.0;
	netParameter->layer[6].blobs = (BlobProto *)malloc(sizeof(BlobProto)*1);
	netParameter->layer[6].blobs_size = 1;
	netParameter->layer[6].blobs[0].width = 0;
	netParameter->layer[6].blobs[0].height = 0;
	netParameter->layer[6].blobs[0].channels = 0;
	netParameter->layer[6].blobs[0].num = 0;
	netParameter->layer[5].pooling_param.pad = 0;
	netParameter->layer[5].pooling_param.pad_h = 0;
	netParameter->layer[5].pooling_param.pad_w = 0;
	netParameter->layer[5].pooling_param.engine = PoolingParameter_Engine_DEFAULT;
	netParameter->layer[5].pooling_param.global_pooling = false;
	netParameter->layer[5].blobs = (BlobProto *)malloc(sizeof(BlobProto)*1);
	netParameter->layer[5].blobs_size = 1;
	netParameter->layer[5].blobs[0].width = 0;
	netParameter->layer[5].blobs[0].height = 0;
	netParameter->layer[5].blobs[0].channels = 0;
	netParameter->layer[5].blobs[0].num = 0;
	netParameter->layer[5].param = (ParamSpec *)malloc(sizeof(ParamSpec)*1);
	netParameter->layer[5].param_size = 1;
	netParameter->layer[5].param[0].decay_mult = 1.0;
	netParameter->layer[5].param[0].lr_mult = 1.0;
	netParameter->layer[4].convolution_param.bias_term = true;
	netParameter->layer[4].convolution_param.pad_h = 0;
	netParameter->layer[4].convolution_param.pad_w = 0;
	netParameter->layer[4].convolution_param.group = 1;
	netParameter->layer[4].convolution_param.engine = ConvolutionParameter_Engine_DEFAULT;
	netParameter->layer[4].convolution_param.axis = 1;
	netParameter->layer[4].convolution_param.force_nd_im2col = false;
	netParameter->layer[4].convolution_param.bias_filler.value = 0;
	netParameter->layer[4].convolution_param.bias_filler.min = 0;
	netParameter->layer[4].convolution_param.bias_filler.max = 1;
	netParameter->layer[4].convolution_param.bias_filler.mean = 0;
	netParameter->layer[4].convolution_param.bias_filler.std = 1;
	netParameter->layer[4].convolution_param.bias_filler.sparse = -1;
	netParameter->layer[4].convolution_param.bias_filler.variance_norm = FillerParameter_VarianceNorm_FAN_IN;
	netParameter->layer[4].convolution_param.weight_filler.value = 0;
	netParameter->layer[4].convolution_param.weight_filler.min = 0;
	netParameter->layer[4].convolution_param.weight_filler.max = 1;
	netParameter->layer[4].convolution_param.weight_filler.mean = 0;
	netParameter->layer[4].convolution_param.weight_filler.std = 1;
	netParameter->layer[4].convolution_param.weight_filler.sparse = -1;
	netParameter->layer[4].convolution_param.weight_filler.variance_norm = FillerParameter_VarianceNorm_FAN_IN;
	netParameter->layer[4].param[1].decay_mult = 1.0;
	netParameter->layer[4].param[0].decay_mult = 1.0;
	netParameter->layer[4].blobs = (BlobProto *)malloc(sizeof(BlobProto)*1);
	netParameter->layer[4].blobs_size = 1;
	netParameter->layer[4].blobs[0].width = 0;
	netParameter->layer[4].blobs[0].height = 0;
	netParameter->layer[4].blobs[0].channels = 0;
	netParameter->layer[4].blobs[0].num = 0;
	netParameter->layer[3].pooling_param.pad = 0;
	netParameter->layer[3].pooling_param.pad_h = 0;
	netParameter->layer[3].pooling_param.pad_w = 0;
	netParameter->layer[3].pooling_param.engine = PoolingParameter_Engine_DEFAULT;
	netParameter->layer[3].pooling_param.global_pooling = false;
	netParameter->layer[3].blobs = (BlobProto *)malloc(sizeof(BlobProto)*1);
	netParameter->layer[3].blobs_size = 1;
	netParameter->layer[3].blobs[0].width = 0;
	netParameter->layer[3].blobs[0].height = 0;
	netParameter->layer[3].blobs[0].channels = 0;
	netParameter->layer[3].blobs[0].num = 0;
	netParameter->layer[3].param = (ParamSpec *)malloc(sizeof(ParamSpec)*1);
	netParameter->layer[3].param_size = 1;
	netParameter->layer[3].param[0].decay_mult = 1.0;
	netParameter->layer[3].param[0].lr_mult = 1.0;
	netParameter->layer[2].convolution_param.bias_term = true;
	netParameter->layer[2].convolution_param.pad_h = 0;
	netParameter->layer[2].convolution_param.pad_w = 0;
	netParameter->layer[2].convolution_param.group = 1;
	netParameter->layer[2].convolution_param.engine = ConvolutionParameter_Engine_DEFAULT;
	netParameter->layer[2].convolution_param.axis = 1;
	netParameter->layer[2].convolution_param.force_nd_im2col = false;
	netParameter->layer[2].convolution_param.bias_filler.value = 0;
	netParameter->layer[2].convolution_param.bias_filler.min = 0;
	netParameter->layer[2].convolution_param.bias_filler.max = 1;
	netParameter->layer[2].convolution_param.bias_filler.mean = 0;
	netParameter->layer[2].convolution_param.bias_filler.std = 1;
	netParameter->layer[2].convolution_param.bias_filler.sparse = -1;
	netParameter->layer[2].convolution_param.bias_filler.variance_norm = FillerParameter_VarianceNorm_FAN_IN;
	netParameter->layer[2].convolution_param.weight_filler.value = 0;
	netParameter->layer[2].convolution_param.weight_filler.min = 0;
	netParameter->layer[2].convolution_param.weight_filler.max = 1;
	netParameter->layer[2].convolution_param.weight_filler.mean = 0;
	netParameter->layer[2].convolution_param.weight_filler.std = 1;
	netParameter->layer[2].convolution_param.weight_filler.sparse = -1;
	netParameter->layer[2].convolution_param.weight_filler.variance_norm = FillerParameter_VarianceNorm_FAN_IN;
	netParameter->layer[2].param[1].decay_mult = 1.0;
	netParameter->layer[2].param[0].decay_mult = 1.0;
	netParameter->layer[2].blobs = (BlobProto *)malloc(sizeof(BlobProto)*1);
	netParameter->layer[2].blobs_size = 1;
	netParameter->layer[2].blobs[0].width = 0;
	netParameter->layer[2].blobs[0].height = 0;
	netParameter->layer[2].blobs[0].channels = 0;
	netParameter->layer[2].blobs[0].num = 0;
	netParameter->layer[1].data_param.rand_skip = 0;
	netParameter->layer[1].data_param.scale = 1;
	netParameter->layer[1].data_param.crop_size = 0;
	netParameter->layer[1].data_param.mirror = false;
	netParameter->layer[1].data_param.force_encoded_color = false;
	netParameter->layer[1].data_param.prefetch = 4;
	netParameter->layer[1].transform_param.mirror = false;
	netParameter->layer[1].transform_param.crop_size = 0;
	netParameter->layer[1].transform_param.crop_h = 0;
	netParameter->layer[1].transform_param.crop_w = 0;
	netParameter->layer[1].transform_param.force_color = false;
	netParameter->layer[1].transform_param.force_gray = false;
	netParameter->layer[1].transform_param.emit_constraint.emit_type = EmitConstraint_EmitType_CENTER;
	netParameter->layer[1].transform_param.noise_param.convert_to_lab = false;
	netParameter->layer[1].transform_param.noise_param.convert_to_hsv = false;
	netParameter->layer[1].transform_param.noise_param.clahe = false;
	netParameter->layer[1].transform_param.noise_param.saltpepper_param.fraction = 0;
	netParameter->layer[1].transform_param.noise_param.saltpepper = false;
	netParameter->layer[1].transform_param.noise_param.erode = false;
	netParameter->layer[1].transform_param.noise_param.posterize = false;
	netParameter->layer[1].transform_param.noise_param.jpeg = -1;
	netParameter->layer[1].transform_param.noise_param.gauss_blur = false;
	netParameter->layer[1].transform_param.noise_param.decolorize = false;
	netParameter->layer[1].transform_param.noise_param.inverse = false;
	netParameter->layer[1].transform_param.noise_param.hist_eq = false;
	netParameter->layer[1].transform_param.noise_param.prob = 0;
	netParameter->layer[1].transform_param.resize_param.pad_mode = ResizeParameter_Pad_mode_CONSTANT;
	netParameter->layer[1].transform_param.resize_param.width = 0;
	netParameter->layer[1].transform_param.resize_param.height = 0;
	netParameter->layer[1].transform_param.resize_param.resize_mode = ResizeParameter_Resize_mode_WARP;
	netParameter->layer[1].transform_param.resize_param.prob = 1;
	netParameter->layer[1].blobs = (BlobProto *)malloc(sizeof(BlobProto)*1);
	netParameter->layer[1].blobs_size = 1;
	netParameter->layer[1].blobs[0].width = 0;
	netParameter->layer[1].blobs[0].height = 0;
	netParameter->layer[1].blobs[0].channels = 0;
	netParameter->layer[1].blobs[0].num = 0;
	netParameter->layer[1].param = (ParamSpec *)malloc(sizeof(ParamSpec)*1);
	netParameter->layer[1].param_size = 1;
	netParameter->layer[1].param[0].decay_mult = 1.0;
	netParameter->layer[1].param[0].lr_mult = 1.0;
	netParameter->layer[0].data_param.rand_skip = 0;
	netParameter->layer[0].data_param.scale = 1;
	netParameter->layer[0].data_param.crop_size = 0;
	netParameter->layer[0].data_param.mirror = false;
	netParameter->layer[0].data_param.force_encoded_color = false;
	netParameter->layer[0].data_param.prefetch = 4;
	netParameter->layer[0].transform_param.mirror = false;
	netParameter->layer[0].transform_param.crop_size = 0;
	netParameter->layer[0].transform_param.crop_h = 0;
	netParameter->layer[0].transform_param.crop_w = 0;
	netParameter->layer[0].transform_param.force_color = false;
	netParameter->layer[0].transform_param.force_gray = false;
	netParameter->layer[0].transform_param.emit_constraint.emit_type = EmitConstraint_EmitType_CENTER;
	netParameter->layer[0].transform_param.noise_param.convert_to_lab = false;
	netParameter->layer[0].transform_param.noise_param.convert_to_hsv = false;
	netParameter->layer[0].transform_param.noise_param.clahe = false;
	netParameter->layer[0].transform_param.noise_param.saltpepper_param.fraction = 0;
	netParameter->layer[0].transform_param.noise_param.saltpepper = false;
	netParameter->layer[0].transform_param.noise_param.erode = false;
	netParameter->layer[0].transform_param.noise_param.posterize = false;
	netParameter->layer[0].transform_param.noise_param.jpeg = -1;
	netParameter->layer[0].transform_param.noise_param.gauss_blur = false;
	netParameter->layer[0].transform_param.noise_param.decolorize = false;
	netParameter->layer[0].transform_param.noise_param.inverse = false;
	netParameter->layer[0].transform_param.noise_param.hist_eq = false;
	netParameter->layer[0].transform_param.noise_param.prob = 0;
	netParameter->layer[0].transform_param.resize_param.pad_mode = ResizeParameter_Pad_mode_CONSTANT;
	netParameter->layer[0].transform_param.resize_param.width = 0;
	netParameter->layer[0].transform_param.resize_param.height = 0;
	netParameter->layer[0].transform_param.resize_param.resize_mode = ResizeParameter_Resize_mode_WARP;
	netParameter->layer[0].transform_param.resize_param.prob = 1;
	netParameter->layer[0].blobs = (BlobProto *)malloc(sizeof(BlobProto)*1);
	netParameter->layer[0].blobs_size = 1;
	netParameter->layer[0].blobs[0].width = 0;
	netParameter->layer[0].blobs[0].height = 0;
	netParameter->layer[0].blobs[0].channels = 0;
	netParameter->layer[0].blobs[0].num = 0;
	netParameter->layer[0].param = (ParamSpec *)malloc(sizeof(ParamSpec)*1);
	netParameter->layer[0].param_size = 1;
	netParameter->layer[0].param[0].decay_mult = 1.0;
	netParameter->layer[0].param[0].lr_mult = 1.0;
	netParameter->layers = (V1LayerParameter *)malloc(sizeof(V1LayerParameter)*1);
	netParameter->layers_size = 1;
	netParameter->layers[0].layer.concat_dim = 1;
	netParameter->layers[0].layer.shuffle_images = false;
	netParameter->layers[0].layer.new_width = 0;
	netParameter->layers[0].layer.new_height = 0;
	netParameter->layers[0].layer.new_channels = 0;
	netParameter->layers[0].layer.new_num = 0;
	CHECK_EXPR_RET(strlen("warp") > PARSE_STR_NAME_SIZE - 1,-1);
	strcpy(netParameter->layers[0].layer.det_crop_mode,"warp");
	netParameter->layers[0].layer.det_context_pad = 0;
	netParameter->layers[0].layer.det_fg_fraction = 0.25;
	netParameter->layers[0].layer.det_bg_threshold = 0.5;
	netParameter->layers[0].layer.det_fg_threshold = 0.5;
	netParameter->layers[0].layer.rand_skip = 0;
	netParameter->layers[0].layer.blobs = (BlobProto *)malloc(sizeof(BlobProto)*1);
	netParameter->layers[0].layer.blobs_size = 1;
	netParameter->layers[0].layer.blobs[0].width = 0;
	netParameter->layers[0].layer.blobs[0].height = 0;
	netParameter->layers[0].layer.blobs[0].channels = 0;
	netParameter->layers[0].layer.blobs[0].num = 0;
	netParameter->layers[0].layer.mirror = false;
	netParameter->layers[0].layer.cropsize = 0;
	netParameter->layers[0].layer.scale = 1;
	netParameter->layers[0].layer.k = 1.;
	netParameter->layers[0].layer.beta = 0.75;
	netParameter->layers[0].layer.alpha = 1.;
	netParameter->layers[0].layer.local_size = 5;
	netParameter->layers[0].layer.dropout_ratio = 0.5;
	netParameter->layers[0].layer.pool = V0LayerParameter_PoolMethod_MAX;
	netParameter->layers[0].layer.stride = 1;
	netParameter->layers[0].layer.group = 1;
	netParameter->layers[0].layer.pad = 0;
	netParameter->layers[0].layer.bias_filler.variance_norm = FillerParameter_VarianceNorm_FAN_IN;
	netParameter->layers[0].layer.bias_filler.sparse = -1;
	netParameter->layers[0].layer.bias_filler.std = 1;
	netParameter->layers[0].layer.bias_filler.mean = 0;
	netParameter->layers[0].layer.bias_filler.max = 1;
	netParameter->layers[0].layer.bias_filler.min = 0;
	netParameter->layers[0].layer.bias_filler.value = 0;
	CHECK_EXPR_RET(strlen("constant") > PARSE_STR_NAME_SIZE - 1,-1);
	strcpy(netParameter->layers[0].layer.bias_filler.type,"constant");
	netParameter->layers[0].layer.weight_filler.variance_norm = FillerParameter_VarianceNorm_FAN_IN;
	netParameter->layers[0].layer.weight_filler.sparse = -1;
	netParameter->layers[0].layer.weight_filler.std = 1;
	netParameter->layers[0].layer.weight_filler.mean = 0;
	netParameter->layers[0].layer.weight_filler.max = 1;
	netParameter->layers[0].layer.weight_filler.min = 0;
	netParameter->layers[0].layer.weight_filler.value = 0;
	CHECK_EXPR_RET(strlen("constant") > PARSE_STR_NAME_SIZE - 1,-1);
	strcpy(netParameter->layers[0].layer.weight_filler.type,"constant");
	netParameter->layers[0].layer.biasterm = true;
	netParameter->layers[0].loss_param.normalization = LossParameter_NormalizationMode_VALID;
	netParameter->layers[0].transform_param.emit_constraint.emit_type = EmitConstraint_EmitType_CENTER;
	netParameter->layers[0].transform_param.noise_param.convert_to_lab = false;
	netParameter->layers[0].transform_param.noise_param.convert_to_hsv = false;
	netParameter->layers[0].transform_param.noise_param.clahe = false;
	netParameter->layers[0].transform_param.noise_param.saltpepper_param.fraction = 0;
	netParameter->layers[0].transform_param.noise_param.saltpepper = false;
	netParameter->layers[0].transform_param.noise_param.erode = false;
	netParameter->layers[0].transform_param.noise_param.posterize = false;
	netParameter->layers[0].transform_param.noise_param.jpeg = -1;
	netParameter->layers[0].transform_param.noise_param.gauss_blur = false;
	netParameter->layers[0].transform_param.noise_param.decolorize = false;
	netParameter->layers[0].transform_param.noise_param.inverse = false;
	netParameter->layers[0].transform_param.noise_param.hist_eq = false;
	netParameter->layers[0].transform_param.noise_param.prob = 0;
	netParameter->layers[0].transform_param.resize_param.pad_mode = ResizeParameter_Pad_mode_CONSTANT;
	netParameter->layers[0].transform_param.resize_param.width = 0;
	netParameter->layers[0].transform_param.resize_param.height = 0;
	netParameter->layers[0].transform_param.resize_param.resize_mode = ResizeParameter_Resize_mode_WARP;
	netParameter->layers[0].transform_param.resize_param.prob = 1;
	netParameter->layers[0].transform_param.force_gray = false;
	netParameter->layers[0].transform_param.force_color = false;
	netParameter->layers[0].transform_param.crop_w = 0;
	netParameter->layers[0].transform_param.crop_h = 0;
	netParameter->layers[0].transform_param.crop_size = 0;
	netParameter->layers[0].transform_param.mirror = false;
	netParameter->layers[0].transform_param.scale = 1;
	CHECK_EXPR_RET(strlen("") > PARSE_STR_NAME_SIZE - 1,-1);
	strcpy(netParameter->layers[0].window_data_param.root_folder,"");
	netParameter->layers[0].window_data_param.cache_images = false;
	CHECK_EXPR_RET(strlen("warp") > PARSE_STR_NAME_SIZE - 1,-1);
	strcpy(netParameter->layers[0].window_data_param.crop_mode,"warp");
	netParameter->layers[0].window_data_param.context_pad = 0;
	netParameter->layers[0].window_data_param.fg_fraction = 0.25;
	netParameter->layers[0].window_data_param.bg_threshold = 0.5;
	netParameter->layers[0].window_data_param.fg_threshold = 0.5;
	netParameter->layers[0].window_data_param.mirror = false;
	netParameter->layers[0].window_data_param.crop_size = 0;
	netParameter->layers[0].window_data_param.scale = 1;
	netParameter->layers[0].threshold_param.threshold = 0;
	netParameter->layers[0].tanh_param.engine = TanHParameter_Engine_DEFAULT;
	netParameter->layers[0].slice_param.slice_dim = 1;
	netParameter->layers[0].slice_param.axis = 1;
	netParameter->layers[0].softmax_param.axis = 1;
	netParameter->layers[0].softmax_param.engine = SoftmaxParameter_Engine_DEFAULT;
	netParameter->layers[0].sigmoid_param.engine = SigmoidParameter_Engine_DEFAULT;
	netParameter->layers[0].relu_param.engine = ReLUParameter_Engine_DEFAULT;
	netParameter->layers[0].relu_param.negative_slope = 0;
	netParameter->layers[0].power_param.shift = 0.0;
	netParameter->layers[0].power_param.scale = 1.0;
	netParameter->layers[0].power_param.power = 1.0;
	netParameter->layers[0].pooling_param.global_pooling = false;
	netParameter->layers[0].pooling_param.engine = PoolingParameter_Engine_DEFAULT;
	netParameter->layers[0].pooling_param.stride = 1;
	netParameter->layers[0].pooling_param.pad_w = 0;
	netParameter->layers[0].pooling_param.pad_h = 0;
	netParameter->layers[0].pooling_param.pad = 0;
	netParameter->layers[0].pooling_param.pool = PoolingParameter_PoolMethod_MAX;
	netParameter->layers[0].mvn_param.eps = 1e-9;
	netParameter->layers[0].mvn_param.across_channels = false;
	netParameter->layers[0].mvn_param.normalize_variance = true;
	netParameter->layers[0].lrn_param.engine = LRNParameter_Engine_DEFAULT;
	netParameter->layers[0].lrn_param.k = 1.;
	netParameter->layers[0].lrn_param.norm_region = LRNParameter_NormRegion_ACROSS_CHANNELS;
	netParameter->layers[0].lrn_param.beta = 0.75;
	netParameter->layers[0].lrn_param.alpha = 1.;
	netParameter->layers[0].lrn_param.local_size = 5;
	netParameter->layers[0].inner_product_param.transpose = false;
	netParameter->layers[0].inner_product_param.axis = 1;
	netParameter->layers[0].inner_product_param.bias_filler.variance_norm = FillerParameter_VarianceNorm_FAN_IN;
	netParameter->layers[0].inner_product_param.bias_filler.sparse = -1;
	netParameter->layers[0].inner_product_param.bias_filler.std = 1;
	netParameter->layers[0].inner_product_param.bias_filler.mean = 0;
	netParameter->layers[0].inner_product_param.bias_filler.max = 1;
	netParameter->layers[0].inner_product_param.bias_filler.min = 0;
	netParameter->layers[0].inner_product_param.bias_filler.value = 0;
	CHECK_EXPR_RET(strlen("constant") > PARSE_STR_NAME_SIZE - 1,-1);
	strcpy(netParameter->layers[0].inner_product_param.bias_filler.type,"constant");
	netParameter->layers[0].inner_product_param.weight_filler.variance_norm = FillerParameter_VarianceNorm_FAN_IN;
	netParameter->layers[0].inner_product_param.weight_filler.sparse = -1;
	netParameter->layers[0].inner_product_param.weight_filler.std = 1;
	netParameter->layers[0].inner_product_param.weight_filler.mean = 0;
	netParameter->layers[0].inner_product_param.weight_filler.max = 1;
	netParameter->layers[0].inner_product_param.weight_filler.min = 0;
	netParameter->layers[0].inner_product_param.weight_filler.value = 0;
	CHECK_EXPR_RET(strlen("constant") > PARSE_STR_NAME_SIZE - 1,-1);
	strcpy(netParameter->layers[0].inner_product_param.weight_filler.type,"constant");
	netParameter->layers[0].inner_product_param.bias_term = true;
	CHECK_EXPR_RET(strlen("") > PARSE_STR_NAME_SIZE - 1,-1);
	strcpy(netParameter->layers[0].image_data_param.root_folder,"");
	netParameter->layers[0].image_data_param.mirror = false;
	netParameter->layers[0].image_data_param.crop_size = 0;
	netParameter->layers[0].image_data_param.scale = 1;
	netParameter->layers[0].image_data_param.is_color = true;
	netParameter->layers[0].image_data_param.new_width = 0;
	netParameter->layers[0].image_data_param.new_height = 0;
	netParameter->layers[0].image_data_param.shuffle = false;
	netParameter->layers[0].image_data_param.rand_skip = 0;
	netParameter->layers[0].image_data_param.batch_size = 1;
	netParameter->layers[0].hinge_loss_param.norm = HingeLossParameter_Norm_L1;
	netParameter->layers[0].hdf5_data_param.shuffle = false;
	netParameter->layers[0].exp_param.shift = 0.0;
	netParameter->layers[0].exp_param.scale = 1.0;
	netParameter->layers[0].exp_param.base = -1.0;
	netParameter->layers[0].eltwise_param.stable_prod_grad = true;
	netParameter->layers[0].eltwise_param.operation = EltwiseParameter_EltwiseOp_SUM;
	netParameter->layers[0].dummy_data_param.data_filler = (FillerParameter *)malloc(sizeof(FillerParameter)*1);
	netParameter->layers[0].dummy_data_param.data_filler_size = 1;
	netParameter->layers[0].dummy_data_param.data_filler[0].variance_norm = FillerParameter_VarianceNorm_FAN_IN;
	netParameter->layers[0].dummy_data_param.data_filler[0].sparse = -1;
	netParameter->layers[0].dummy_data_param.data_filler[0].std = 1;
	netParameter->layers[0].dummy_data_param.data_filler[0].mean = 0;
	netParameter->layers[0].dummy_data_param.data_filler[0].max = 1;
	netParameter->layers[0].dummy_data_param.data_filler[0].min = 0;
	netParameter->layers[0].dummy_data_param.data_filler[0].value = 0;
	CHECK_EXPR_RET(strlen("constant") > PARSE_STR_NAME_SIZE - 1,-1);
	strcpy(netParameter->layers[0].dummy_data_param.data_filler[0].type,"constant");
	netParameter->layers[0].dropout_param.dropout_ratio = 0.5;
	netParameter->layers[0].data_param.prefetch = 4;
	netParameter->layers[0].data_param.force_encoded_color = false;
	netParameter->layers[0].data_param.mirror = false;
	netParameter->layers[0].data_param.crop_size = 0;
	netParameter->layers[0].data_param.scale = 1;
	netParameter->layers[0].data_param.backend = DataParameter_DB_LEVELDB;
	netParameter->layers[0].data_param.rand_skip = 0;
	netParameter->layers[0].convolution_param.force_nd_im2col = false;
	netParameter->layers[0].convolution_param.axis = 1;
	netParameter->layers[0].convolution_param.engine = ConvolutionParameter_Engine_DEFAULT;
	netParameter->layers[0].convolution_param.bias_filler.variance_norm = FillerParameter_VarianceNorm_FAN_IN;
	netParameter->layers[0].convolution_param.bias_filler.sparse = -1;
	netParameter->layers[0].convolution_param.bias_filler.std = 1;
	netParameter->layers[0].convolution_param.bias_filler.mean = 0;
	netParameter->layers[0].convolution_param.bias_filler.max = 1;
	netParameter->layers[0].convolution_param.bias_filler.min = 0;
	netParameter->layers[0].convolution_param.bias_filler.value = 0;
	CHECK_EXPR_RET(strlen("constant") > PARSE_STR_NAME_SIZE - 1,-1);
	strcpy(netParameter->layers[0].convolution_param.bias_filler.type,"constant");
	netParameter->layers[0].convolution_param.weight_filler.variance_norm = FillerParameter_VarianceNorm_FAN_IN;
	netParameter->layers[0].convolution_param.weight_filler.sparse = -1;
	netParameter->layers[0].convolution_param.weight_filler.std = 1;
	netParameter->layers[0].convolution_param.weight_filler.mean = 0;
	netParameter->layers[0].convolution_param.weight_filler.max = 1;
	netParameter->layers[0].convolution_param.weight_filler.min = 0;
	netParameter->layers[0].convolution_param.weight_filler.value = 0;
	CHECK_EXPR_RET(strlen("constant") > PARSE_STR_NAME_SIZE - 1,-1);
	strcpy(netParameter->layers[0].convolution_param.weight_filler.type,"constant");
	netParameter->layers[0].convolution_param.group = 1;
	netParameter->layers[0].convolution_param.pad_w = 0;
	netParameter->layers[0].convolution_param.pad_h = 0;
	netParameter->layers[0].convolution_param.bias_term = true;
	netParameter->layers[0].contrastive_loss_param.legacy_version = false;
	netParameter->layers[0].contrastive_loss_param.margin = 1.0;
	netParameter->layers[0].concat_param.concat_dim = 1;
	netParameter->layers[0].concat_param.axis = 1;
	netParameter->layers[0].argmax_param.top_k = 1;
	netParameter->layers[0].argmax_param.out_max_val = false;
	netParameter->layers[0].accuracy_param.axis = 1;
	netParameter->layers[0].accuracy_param.top_k = 1;
	netParameter->layers[0].blobs = (BlobProto *)malloc(sizeof(BlobProto)*1);
	netParameter->layers[0].blobs_size = 1;
	netParameter->layers[0].blobs[0].width = 0;
	netParameter->layers[0].blobs[0].height = 0;
	netParameter->layers[0].blobs[0].channels = 0;
	netParameter->layers[0].blobs[0].num = 0;
	netParameter->state.level = 0;
	netParameter->state.phase = TEST;
	return 0;

}
